const { defineProps, defineSlots, defineEmits, defineExpose, defineModel, defineOptions, withDefaults, } = await import('vue');
const __VLS_fnComponent = (await import('vue')).defineComponent({});
;
let __VLS_functionalComponentProps;
function __VLS_template() {
    let __VLS_ctx;
    /* Components */
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("bg-[#F0F3F7]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container max-w-screen-lg px-4 py-16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-4xl xl:text-5xl font-eina-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("block mt-2 xl:mt-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("mt-5 text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("hidden grid-cols-3 gap-2 my-10 md:grid md:gap-5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative col-span-1 p-5 space-y-2 overflow-hidden text-center bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-2xl font-bold font-eina-semi-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-sm") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex justify-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("absolute mx-auto h-72") }, src: ("/asset/feature/USPs (1).png"), ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid col-span-2 gap-5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid grid-cols-3 gap-5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative col-span-1 p-5 overflow-hidden text-center bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-2xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex justify-center h-28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("absolute h-40") }, src: ("/asset/feature/USPs (6).png"), ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-2 p-5 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-span-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("mb-3 text-2xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-span-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("absolute h-40") }, src: ("/asset/feature/USPs (3).png"), ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid grid-cols-3 gap-5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-1 gap-5 py-2 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("h-20 col-span-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("h-20 absolute left-[-20px]") }, src: ("/asset/feature/USPs (2).png"), ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center col-span-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-1 gap-5 py-2 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("h-20 col-span-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("h-20 absolute left-[-20px]") }, src: ("/asset/feature/USPs (4).png"), ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center col-span-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-1 gap-5 py-2 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("h-20 col-span-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("h-20 absolute left-[-10px]") }, src: ("/asset/feature/USPs (5).png"), ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center col-span-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("space-y-2 md:hidden") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid grid-cols-3 gap-2 mt-5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative col-span-2 p-5 space-y-2 overflow-hidden text-center bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-2xl font-bold font-eina-semi-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-sm") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex justify-center h-24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("absolute mx-auto h-36") }, src: ("/asset/feature/USPs (1).png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative col-span-1 px-2 py-5 overflow-hidden text-center bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex justify-center h-28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("absolute h-40") }, src: ("/asset/feature/USPs (6).png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-2 p-5 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-span-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("mb-2 text-xl font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-sm") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-span-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("absolute h-28") }, src: ("/asset/feature/USPs (3).png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid grid-cols-3 col-span-3 gap-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-1 gap-5 py-2 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-span-1 h-14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("h-14 absolute left-[-20px]") }, src: ("/asset/feature/USPs (2).png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center col-span-2 h-14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-sm font-eina-semi-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-1 gap-5 py-2 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-span-1 h-14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("h-14 absolute left-[-20px]") }, src: ("/asset/feature/USPs (4).png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center col-span-2 h-14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-sm font-bold font-eina-semi-bold ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative grid grid-cols-3 col-span-1 gap-5 py-2 overflow-hidden bg-white rounded-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("h-12 col-span-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("h-12 absolute left-[-10px]") }, src: ("/asset/feature/USPs (5).png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center h-12 col-span-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-sm font-bold font-eina-semi-bold ") }, });
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['bg-[#F0F3F7]'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['max-w-screen-lg'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-16'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['text-4xl'];
        __VLS_styleScopedClasses['xl:text-5xl'];
        __VLS_styleScopedClasses['font-eina-bold'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['mt-2'];
        __VLS_styleScopedClasses['xl:mt-4'];
        __VLS_styleScopedClasses['mt-5'];
        __VLS_styleScopedClasses['text-base'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['hidden'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['gap-2'];
        __VLS_styleScopedClasses['my-10'];
        __VLS_styleScopedClasses['md:grid'];
        __VLS_styleScopedClasses['md:gap-5'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['p-5'];
        __VLS_styleScopedClasses['space-y-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['h-72'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['p-5'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['h-28'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['h-40'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['p-5'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['mb-3'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['h-40'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['py-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['h-20'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['h-20'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['left-[-20px]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['text-xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['py-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['h-20'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['h-20'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['left-[-20px]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['text-xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['py-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['h-20'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['h-20'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['left-[-10px]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['text-xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['space-y-2'];
        __VLS_styleScopedClasses['md:hidden'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['gap-2'];
        __VLS_styleScopedClasses['mt-5'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['p-5'];
        __VLS_styleScopedClasses['space-y-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['h-24'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['h-36'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['px-2'];
        __VLS_styleScopedClasses['py-5'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['text-xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['h-28'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['h-40'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['p-5'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['mb-2'];
        __VLS_styleScopedClasses['text-xl'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['h-28'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-3'];
        __VLS_styleScopedClasses['gap-2'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['py-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['h-14'];
        __VLS_styleScopedClasses['h-14'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['left-[-20px]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['h-14'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['py-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['h-14'];
        __VLS_styleScopedClasses['h-14'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['left-[-20px]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['h-14'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['grid'];
        __VLS_styleScopedClasses['grid-cols-3'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['gap-5'];
        __VLS_styleScopedClasses['py-2'];
        __VLS_styleScopedClasses['overflow-hidden'];
        __VLS_styleScopedClasses['bg-white'];
        __VLS_styleScopedClasses['rounded-md'];
        __VLS_styleScopedClasses['h-12'];
        __VLS_styleScopedClasses['col-span-1'];
        __VLS_styleScopedClasses['h-12'];
        __VLS_styleScopedClasses['absolute'];
        __VLS_styleScopedClasses['left-[-10px]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['h-12'];
        __VLS_styleScopedClasses['col-span-2'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['font-bold'];
        __VLS_styleScopedClasses['font-eina-semi-bold'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    let __VLS_name;
    let __VLS_defineComponent;
    const __VLS_internalComponent = __VLS_defineComponent({
        setup() {
            return {};
        },
    });
}
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
;
